<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2021 Amasty (https://www.amasty.com)
 * @package Amasty_Rewards
 */
?>
<?php
/* @var $block \Magento\Catalog\Block\Adminhtml\Product\Edit\NewCategory */
?>
<div id="<?php /* @escapeNotVerified */ echo $block->getNameInLayout() ?>" style="display:none">
    <?php echo $block->getFormHtml();?>
    <?php echo $block->getAfterElementHtml();?>
</div>
